name: Update Roles

on:
  schedule:
    - cron:  '0 0 * * *'
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true
    - name: Get Updated Roles
      uses: Azure/powershell@v1
      with:
        inlineScript: |
          Set-Location $ENV:GITHUB_WORKSPACE
          Write-Host "workspace: $ENV:GITHUB_WORKSPACE"
          dir
          ./src/Get-RbacRoles.ps1
        azPSVersion: latest
    - name: Commit Changes
      run: |
        cd $GITHUB_WORKSPACE
        now=$(date)
        git config --global user.email "macporebski@gmail.com"
        git config --global user.name "Maciej Porebski"
        git add --all
        if [ -n "$(git status --porcelain)" ]
        then
          git commit -a -m "Update RBAC Roles $now"
          git push
        fi